language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
script:
  - script/build
xcode_project: ReactiveCollections.xcodeproj
matrix:
  include:
    - xcode_scheme: ReactiveCollections-macOS
      env:
        - XCODE_SDK=macosx
        - XCODE_ACTION="build test"
        - XCODE_DESTINATION="arch=x86_64"
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      install:
        - carthage bootstrap --no-use-binaries --platform macOS
    - xcode_scheme: ReactiveCollections-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 7"
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      install:
        - carthage bootstrap --no-use-binaries --platform iOS
    - xcode_scheme: ReactiveCollections-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 5"
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      install:
        - carthage bootstrap --no-use-binaries --platform iOS
    - xcode_scheme: ReactiveCollections-tvOS
      env:
        - XCODE_SDK=appletvsimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      install:
        - carthage bootstrap --no-use-binaries --platform tvOS
    - xcode_scheme: ReactiveCollections-watchOS
      env:
        - XCODE_SDK=watchsimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=watchOS Simulator,name=Apple Watch - 38mm,OS=2.2"
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      install:
        - carthage bootstrap --no-use-binaries --platform watchOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage bootstrap --no-use-binaries --no-skip-current --platform macOS
      env:
        - JOB=CARTHAGE-macOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage bootstrap --no-use-binaries --no-skip-current --platform iOS
      env:
        - JOB=CARTHAGE-iOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage bootstrap --no-use-binaries --no-skip-current --platform tvOS
      env:
        - JOB=CARTHAGE-tvOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage bootstrap --no-use-binaries --no-skip-current --platform watchOS
      env:
        - JOB=CARTHAGE-watchOS
    - script:
      - pod repo update --silent
      - pod lib lint ReactiveCollections.podspec
      env:
        - JOB=PODSPEC
    - os: osx
      language: generic
      script:
        - swift build
        - SWIFTPM_TEST_ReactiveCollections=YES swift test
      env:
        - JOB=SWIFTPM_DARWIN
#    - os: linux
#      language: generic
#      sudo: required
#      dist: trusty
#      before_install:
#        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
#      script:
#        - swift build
#        - SWIFTPM_TEST_ReactiveCollections=YES swift test
#      env: JOB=SWIFTPM_LINUX
