language: objective-c
osx_image: xcode8.2
before_install: true
install: true
git:
  submodules: false
branches:
  only:
    - master
before_script:
  - git submodule update --init --recursive
script:
  - script/build
xcode_workspace: ReactiveCollections.xcworkspace
matrix:
  include:
    - xcode_scheme: ReactiveCollections-macOS
      env:
        - XCODE_SDK=macosx
        - XCODE_ACTION="build test"
        - XCODE_DESTINATION="arch=x86_64"
        - XCODE_PLAYGROUND_TARGET="x86_64-apple-macosx10.10"
    - xcode_scheme: ReactiveCollections-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s,OS=10.1"
    - xcode_scheme: ReactiveCollections-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 5,OS=10.1"
    - xcode_scheme: ReactiveCollections-tvOS
      env:
        - XCODE_SDK=appletvsimulator
        - XCODE_ACTION="build-for-testing test-without-building"
        - XCODE_DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"
    - xcode_scheme: ReactiveCollections-watchOS
      env:
        - XCODE_SDK=watchsimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=watchOS Simulator,name=Apple Watch - 38mm"
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform mac
      env:
        - JOB=CARTHAGE-macOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform iOS
      env:
        - JOB=CARTHAGE-iOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform tvOS
      env:
        - JOB=CARTHAGE-tvOS
    - script:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        - carthage build --no-skip-current --platform watchOS
      env:
        - JOB=CARTHAGE-watchOS
    - script:
      - gem install cocoapods -v 1.1.1
      - pod repo update --silent
      - pod lib lint --allow-warnings
      env:
        - JOB=PODSPEC
    - os: osx
      language: generic
      script:
        - swift build
      env:
        - JOB=SWIFTPM_DARWIN
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - mv .Package.test.swift Package.swift
        - swift build
        - swift test
      env: JOB=SWIFTPM_LINUX
