#!/bin/bash

# CI build script
#
# https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/script/build
#
# Copyright (c) 2012 - 2016, GitHub, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

BUILD_DIRECTORY="build"
CONFIGURATION=Release

if [[ -z $TRAVIS_XCODE_PROJECT ]]; then
    echo "Error: \$TRAVIS_XCODE_PROJECT is not set."
    exit 1
fi

if [[ -z $TRAVIS_XCODE_SCHEME ]]; then
    echo "Error: \$TRAVIS_XCODE_SCHEME is not set!"
    exit 1
fi

if [[ "$TRAVIS_XCODE_SCHEME" == "ReactiveCollections-macOS" ]]; then
    XCODE_SDK=macosx
    XCODE_ACTION="build test"
    XCODE_DESTINATION="arch=x86_64"
fi

if [[ "$TRAVIS_XCODE_SCHEME" == "ReactiveCollections-iOS" ]]; then
    XCODE_SDK=iphonesimulator
    XCODE_ACTION="build-for-testing test-without-building"
    XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 7"
fi

if [[ "$TRAVIS_XCODE_SCHEME" == "ReactiveCollections-tvOS" ]]; then
    XCODE_SDK=appletvsimulator
    XCODE_ACTION="build-for-testing test-without-building"
    XCODE_DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"
fi

if [[ "$TRAVIS_XCODE_SCHEME" == "ReactiveCollections-watchOS" ]]; then
    XCODE_SDK=watchsimulator
    XCODE_ACTION=build
    XCODE_DESTINATION="platform=watchOS Simulator,name=Apple Watch - 38mm,OS=2.2"
fi

if [[ -z "$XCODE_SDK" ]]; then
    echo "Unrecognized scheme: $TRAVIS_XCODE_SCHEME."
    exit 1
fi

set -o pipefail
xcodebuild $XCODE_ACTION \
    -project "$TRAVIS_XCODE_PROJECT" \
    -scheme "$TRAVIS_XCODE_SCHEME" \
    -sdk "$XCODE_SDK" \
    -destination "$XCODE_DESTINATION" \
    -derivedDataPath "${BUILD_DIRECTORY}" \
    -configuration $CONFIGURATION \
    ENABLE_TESTABILITY=YES \
    GCC_GENERATE_DEBUGGING_SYMBOLS=NO \
    RUN_CLANG_STATIC_ANALYZER=NO | xcpretty
result=$?

if [ "$result" -ne 0 ]; then
    exit $result
fi
